version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: reservation-service-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: reservation_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: